spring.application.name=APIPUBLICA
server.port=${PORT:8100}
spring.main.lazy-initialization=true

spring.datasource.url=jdbc:mysql://root:dUPppXUAzMaGLvzuFbGlqIwkjLywFUrr@nozomi.proxy.rlwy.net:23271/railway
spring.datasource.username=root
spring.datasource.password=dUPppXUAzMaGLvzuFbGlqIwkjLywFUrr
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuracion de JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

